version: '3.5'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8301:80"
            - "4401:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: laravelvue_php
        user: "${UID}"
        volumes:
          - ./:/var/www
          - ./data/composer:/.composer
          - ./logs/laravel:/var/www/var/logs:cached
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: discover9100Ylaravue
            MYSQL_DATABASE: discover_laravelvue
        ports:
            - "8901:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql